name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: public

      - name: Cleanup
        run: npm ci --only=prod

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Restore artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifact

      - name: Run tests
        run: npm test

This is the workflow file contents that you can directly copy into the workflow.yaml file. It will build and run the application and run the tests if present in the repository.